---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-6.5
  - name: centos-7.1

suites:
  - name: replicated1
    driver:
      ipaddress: 192.168.10.10
      vagrantfile_erb: test/integration/Vagrantfile.erb
      vm_hostname: gluster1
      additional_disk: 
        size: 10
    run_list:
      - recipe[testcookbook::set_hostname]
      - recipe[gluster::server]
    attributes:
      gluster:
        server:
          brick_mount_path: "/data"
          disks:
            - sdb
          volumes:
            gv0:
              peers: 
                - "gluster2"
                - "gluster1"
              replica_count: 2
              volume_type: "replicated"

  - name: replicated2
    driver:
      ipaddress: 192.168.10.20
      vagrantfile_erb: test/integration/Vagrantfile.erb
      vm_hostname: gluster2
      additional_disk: 
        size: 10
    run_list:
      - recipe[testcookbook::set_hostname]
      - recipe[gluster::server]
    attributes:
      gluster:
        server:
          disks:
            - sdb
          brick_mount_path: "/data"
          volumes:
            gv0:
              peers: 
                - "gluster2"
                - "gluster1"
              replica_count: 2
              volume_type: "replicated"

  - name: distributed1
    driver:
      ipaddress: 192.168.10.10
      vagrantfile_erb: test/integration/Vagrantfile.erb
      vm_hostname: gluster1
      additional_disk: 
        size: 10
    run_list:
      - recipe[testcookbook::set_hostname]
      - recipe[gluster::server]
    attributes:
      gluster:
        server:
          brick_mount_path: "/data"
          disks:
            - sdb
          volumes:
            gv0:
              peers: 
                - "gluster2"
                - "gluster1"
              replica_count: 2
              volume_type: "distributed"

  - name: distributed2
    driver:
      ipaddress: 192.168.10.20
      vagrantfile_erb: test/integration/Vagrantfile.erb
      vm_hostname: gluster2
      additional_disk: 
        size: 10
    run_list:
      - recipe[testcookbook::set_hostname]
      - recipe[gluster::server]
    attributes:
      gluster:
        server:
          disks:
            - sdb
          brick_mount_path: "/data"
          volumes:
            gv0:
              peers: 
                - "gluster2"
                - "gluster1"
              replica_count: 2
              volume_type: "distributed"

  - name: distributed-replicated1
    driver:
      ipaddress: 192.168.10.10
      vagrantfile_erb: test/integration/Vagrantfile.erb
      vm_hostname: gluster1
      additional_disk: 
        size: 10
    run_list:
      - recipe[testcookbook::set_hostname]
      - recipe[gluster::server]
    attributes:
      gluster:
        server:
          brick_mount_path: "/data"
          disks:
            - sdb
          volumes:
            gv0:
              peers: 
                - "gluster4"
                - "gluster3"
                - "gluster2"
                - "gluster1"
              replica_count: 2
              volume_type: "distributed-replicated"

  - name: distributed-replicated2
    driver:
      ipaddress: 192.168.10.20
      vagrantfile_erb: test/integration/Vagrantfile.erb
      vm_hostname: gluster2
      additional_disk: 
        size: 10
    run_list:
      - recipe[testcookbook::set_hostname]
      - recipe[gluster::server]
    attributes:
      gluster:
        server:
          disks:
            - sdb
          brick_mount_path: "/data"
          volumes:
            gv0:
              peers: 
                - "gluster4"
                - "gluster3"
                - "gluster2"
                - "gluster1"
              replica_count: 2
              volume_type: "distributed-replicated"

  - name: distributed-replicated3
    driver:
      ipaddress: 192.168.10.30
      vagrantfile_erb: test/integration/Vagrantfile.erb
      vm_hostname: gluster3
      additional_disk: 
        size: 10
    run_list:
      - recipe[testcookbook::set_hostname]
      - recipe[gluster::server]
    attributes:
      gluster:
        server:
          brick_mount_path: "/data"
          disks:
            - sdb
          volumes:
            gv0:
              peers: 
                - "gluster4"
                - "gluster3"
                - "gluster2"
                - "gluster1"
              replica_count: 2
              volume_type: "distributed-replicated"

  - name: distributed-replicated4
    driver:
      ipaddress: 192.168.10.40
      vagrantfile_erb: test/integration/Vagrantfile.erb
      vm_hostname: gluster4
      additional_disk: 
        size: 10
    run_list:
      - recipe[testcookbook::set_hostname]
      - recipe[gluster::server]
    attributes:
      gluster:
        server:
          disks:
            - sdb
          brick_mount_path: "/data"
          volumes:
            gv0:
              peers: 
                - "gluster4"
                - "gluster3"
                - "gluster2"
                - "gluster1"
              replica_count: 2
              volume_type: "distributed-replicated"

  - name: striped1
    driver:
      ipaddress: 192.168.10.10
      vagrantfile_erb: test/integration/Vagrantfile.erb
      vm_hostname: gluster1
      additional_disk: 
        size: 10
    run_list:
      - recipe[testcookbook::set_hostname]
      - recipe[gluster::server]
    attributes:
      gluster:
        server:
          brick_mount_path: "/data"
          disks:
            - sdb
          volumes:
            gv0:
              peers: 
                - "gluster2"
                - "gluster1"
              replica_count: 2
              volume_type: "striped"

  - name: striped2
    driver:
      ipaddress: 192.168.10.20
      vagrantfile_erb: test/integration/Vagrantfile.erb
      vm_hostname: gluster2
      additional_disk: 
        size: 10
    run_list:
      - recipe[testcookbook::set_hostname]
      - recipe[gluster::server]
    attributes:
      gluster:
        server:
          disks:
            - sdb
          brick_mount_path: "/data"
          volumes:
            gv0:
              peers: 
                - "gluster2"
                - "gluster1"
              replica_count: 2
              volume_type: "striped"

